version: '3.8'

services:
  ebookmanager:
    image: ghcr.io/hvmzx/ebookmanager:latest
    container_name: ebookmanager
    environment:
      - MANGA_MONITORING=true
      - BOOK_MONITORING=true
      - SCAN_INTERVAL=5
      - KCC_OPTIONS=-p K
    volumes:
      - ~/Downloads/ebooks:/ebooks